https://www.kaggle.com/c/siim-isic-melanoma-classification/discussion/175614

In [1]:
import numpy as np 
import pandas as pd 

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/lets-get-rid-of-the-patients-catboost/probs_73_0_1.csv
/kaggle/input/lets-get-rid-of-the-patients-catboost/submission_432_0_1.csv
/kaggle/input/lets-get-rid-of-the-patients-catboost/probs_32_1_4.csv
/kaggle/input/lets-get-rid-of-the-patients-catboost/probs.csv
/kaggle/input/lets-get-rid-of-the-patients-catboost/submission_32_0_0.csv
/kaggle/input/lets-get-rid-of-the-patients-catboost/submission_432_4_2.csv
/kaggle/input/lets-get-rid-of-the-patients-catboost/probs_32_3_3.csv
/kaggle/input/lets-get-rid-of-the-patients-catboost/probs_432_2_1.csv
/kaggle/input/lets-get-rid-of-the-patients-catboost/probs_432_1_3.csv
/kaggle/input/lets-get-rid-of-the-patients-catboost/probs_432_1_0.csv
/kaggle/input/lets-get-rid-of-the-patients-catboost/submission_32_1_4.csv
/kaggle/input/lets-get-rid-of-the-patients-catboost/probs_32_2_3.csv
/kaggle/input/lets-get-rid-of-the-patients-catboost/probs_73_0_4.csv
/kaggle/input/lets-get-rid-of-the-patients-catboost/probs_432_4_3.csv
/kaggle/input/l

# Generate Submission File

In [2]:
def generate_submission_file(probs_df):
    
    submission = pd.read_csv('../input/healthcareanalyticsii/sample_submission.csv')

    submission['Stay'] =  np.argmax(probs_df.iloc[:,1:].values,axis =1)

    submission['Stay'] = submission['Stay'].map(inv_dic)
    
    submission.to_csv('submission.csv',index=False)

    print(submission.head())

In [3]:
def get_probs_file_name(fname,model):
    
    if model == 'lgb':
        
        fpath = '../input/lets-get-rid-of-the-patients/probs' + fname[10:]
        
    if model == 'xgb':
        
        fpath = '../input/lets-get-rid-of-the-patients-xgboost/probs' + fname[10:]
        
    if model == 'catboost':
        
        fpath = '../input/lets-get-rid-of-the-patients-catboost/probs' + fname[10:]
        
    if model == 'dcn':
        
        fpath = '../input/a-model-built-on-garbage-deeptables-dcn/probs' + fname[10:]
    
    if model == 'dnn':
        
        fpath = '../input/a-model-built-on-garbage-deeptables/probs' + fname[10:]
        
    if model == 'pnn':
        
        fpath = '../input/a-model-built-on-garbage-deeptables-pnn/probs' + fname[10:]
        
    
    return fpath

In [4]:
sample_probs_file = pd.read_csv('../input/lets-get-rid-of-the-patients-catboost/probs_32_0_0.csv')

sample_probs_file.head()

case_id      0-10     11-20     21-30     31-40     41-50     51-60  \
0   318439  0.316506  0.140039  0.247529  0.129634  0.050494  0.064536   
1   318440  0.000516  0.024589  0.011350  0.210735  0.015387  0.553362   
2   318441  0.155782  0.260197  0.377515  0.130934  0.043259  0.021716   
3   318442  0.025929  0.195001  0.599313  0.114527  0.026103  0.032513   
4   318443  0.000512  0.027822  0.016424  0.188868  0.007449  0.649793   

      61-70     71-80     81-90    91-100  More than 100 Days  
0  0.004264  0.027827  0.007519  0.002446            0.009206  
1  0.002588  0.135286  0.012499  0.025461            0.008228  
2  0.004337  0.003410  0.000760  0.000846            0.001244  
3  0.002339  0.002508  0.000784  0.000531            0.000450  
4  0.001199  0.090779  0.004268  0.005886            0.007001

In [5]:
inv_dic ={}

for i in range(len(sample_probs_file.columns[1:])):
    
    inv_dic[i] = sample_probs_file.columns[i+1]

In [6]:
model_stats_catboost = pd.read_csv('../input/lets-get-rid-of-the-patients-catboost/model_stats.csv')

model_stats_lgb = pd.read_csv('../input/lets-get-rid-of-the-patients/model_stats.csv')

model_stats_xgb = pd.read_csv('../input/lets-get-rid-of-the-patients-xgboost/model_stats.csv')

model_stats_dcn = pd.read_csv('../input/a-model-built-on-garbage-deeptables-dcn/model_stats.csv')

model_stats_dnn = pd.read_csv('../input/a-model-built-on-garbage-deeptables/model_stats.csv')

model_stats_pnn = pd.read_csv('../input/a-model-built-on-garbage-deeptables-pnn/model_stats.csv')

In [7]:
##ALL
probs_file_cat = pd.read_csv('../input/lets-get-rid-of-the-patients-catboost/probs.csv')

probs_file_lgb = pd.read_csv('../input/lets-get-rid-of-the-patients/probs.csv')

probs_file_xgb = pd.read_csv('../input/lets-get-rid-of-the-patients-xgboost/probs.csv')

probs_file_dcn = pd.read_csv('../input/a-model-built-on-garbage-deeptables-dcn/probs.csv')

probs_file_dnn = pd.read_csv('../input/a-model-built-on-garbage-deeptables/probs.csv')

probs_file_pnn = pd.read_csv('../input/a-model-built-on-garbage-deeptables-pnn/probs.csv')

In [8]:
#Public LB==44.2814928313451
#sample_probs_file.iloc[:,1:] = probs_file_dcn.iloc[:,1:] + probs_file_pnn.iloc[:,1:]

#sample_probs_file.head()

In [9]:
#generate_submission_file(sample_probs_file)

# Get Min Loss Indices

In [10]:
min_loss_index_lgb = np.argsort(model_stats_catboost.validation_loss.values)

min_loss_index_lgb

array([37, 68, 69, 38, 21, 65, 39, 35, 24, 15,  0, 59, 67, 22, 47, 50, 66,
       49, 45, 31, 54, 52, 17, 46, 28, 71,  2, 13, 33, 62, 51, 60, 36, 25,
       10, 53,  4, 73,  3, 57, 63,  7, 74, 70, 58, 44, 12, 19, 61, 11, 32,
        1, 26, 72, 18, 16, 34, 27, 30, 43, 20,  8, 48, 29, 14, 64, 40, 23,
        5, 42, 55,  9, 56, 41,  6])

In [11]:
min_loss_index_xgb = np.argsort(model_stats_xgb.validation_loss.values)

min_loss_index_xgb

array([68, 67, 69, 66, 65, 38, 35, 37, 36, 53, 39, 45, 52, 24, 51, 21, 22,
       48, 20, 23, 46, 16,  2,  3, 47, 54, 15, 18,  1, 50,  0, 17, 57, 33,
       59, 19, 56,  4, 26, 49, 25, 58, 32, 28, 31, 55, 30, 12, 13, 11, 27,
       10, 29, 63, 14, 40, 62, 34, 61, 60, 64, 41, 42, 43, 71, 72, 70, 74,
       44,  6, 73,  8,  5,  7,  9])

In [12]:
min_loss_index_cat = np.argsort(model_stats_catboost.validation_loss.values)

min_loss_index_cat

array([37, 68, 69, 38, 21, 65, 39, 35, 24, 15,  0, 59, 67, 22, 47, 50, 66,
       49, 45, 31, 54, 52, 17, 46, 28, 71,  2, 13, 33, 62, 51, 60, 36, 25,
       10, 53,  4, 73,  3, 57, 63,  7, 74, 70, 58, 44, 12, 19, 61, 11, 32,
        1, 26, 72, 18, 16, 34, 27, 30, 43, 20,  8, 48, 29, 14, 64, 40, 23,
        5, 42, 55,  9, 56, 41,  6])

In [13]:
min_loss_index_dcn = np.argsort(model_stats_dcn.validation_loss.values)

min_loss_index_dcn

array([67, 35, 22, 21, 66, 37, 38, 68, 69, 36, 24, 65, 18, 23, 20, 29, 27,
       16, 19, 54, 28, 39, 45, 47,  0,  1, 50, 34, 46,  3, 48, 53, 10, 15,
       57, 56,  4, 13, 14, 31, 59,  2, 58, 51, 63, 25, 32, 17, 62, 64, 71,
       61, 49, 30, 11, 55, 74, 52, 72, 12, 41, 26, 70, 73, 40, 43, 33, 44,
        6,  7, 60,  8,  9, 42,  5])

In [14]:
min_loss_index_dnn = np.argsort(model_stats_dnn.validation_loss.values)

min_loss_index_dnn

array([65, 68, 67, 39, 69, 37, 38, 20, 35, 66, 36, 23, 22, 27, 21, 18, 24,
       28, 48, 25, 16, 29, 49, 19,  4, 26, 45,  0, 15, 57, 59, 50, 46, 51,
       54, 17,  3, 63, 55, 31, 30, 32, 58, 47, 61, 14,  2,  1, 56, 62, 34,
       11, 10, 13, 64, 33, 60, 70, 12, 74, 52, 72, 73, 71, 53, 40, 43, 44,
       41,  8,  5,  7,  9, 42,  6])

In [15]:
min_loss_index_pnn = np.argsort(model_stats_pnn.validation_loss.values)

min_loss_index_pnn

array([69, 68, 67, 24, 36, 65, 23, 21, 37, 38, 66, 22, 35, 39, 20, 26, 49,
       27, 47, 28, 45, 48, 16, 57, 58,  1, 17, 55, 46, 19,  2, 15, 29, 59,
        4, 56,  3, 50, 54, 25, 18, 52, 61, 32, 53, 34,  0, 30, 51, 31, 60,
       63, 64, 33, 72, 14, 70, 11, 12, 10, 13, 62, 71, 42, 74, 43, 73, 44,
       41,  7, 40,  5,  6,  9,  8])

# Get Max Accuracy indices

In [16]:
max_accuracy_index_catboost = np.argsort(-model_stats_catboost.accuracy.values)

max_accuracy_index_catboost

array([68, 37,  0, 49, 65, 38,  4, 71, 66, 13, 46, 51, 45, 69, 12, 24,  2,
       47,  3, 10, 35, 48, 36, 33, 54, 25,  1, 14, 21, 59, 28, 39, 50, 67,
       53, 31, 27, 52,  8, 63, 70, 74, 44, 15, 62, 26, 32, 73,  7, 34, 29,
       22, 61, 20, 17, 11,  5, 57, 72,  9, 23, 58, 18, 30, 60, 42, 40, 64,
       56, 43, 55, 16,  6, 19, 41])

In [17]:
max_accuracy_index_lgb = np.argsort(-model_stats_lgb.accuracy.values)

max_accuracy_index_lgb

array([67, 69, 38, 48, 65, 68, 66, 46, 37, 36, 35, 45, 10, 49, 26, 50, 47,
       29, 39, 27,  9, 23, 52,  1, 13, 11, 28, 21, 53, 25,  6, 14, 12, 64,
       22, 62,  4,  2, 34, 33,  5, 24, 30,  8, 31, 20,  0, 41, 32, 57, 44,
       54,  7, 71, 63, 73, 19,  3, 60, 70, 18, 59, 51, 55, 56, 61, 17, 72,
       74, 40, 42, 58, 16, 43, 15])

In [18]:
max_accuracy_index_xgb = np.argsort(-model_stats_xgb.accuracy.values)

max_accuracy_index_xgb

array([65, 68, 69, 66, 67, 14, 37, 46, 45,  4, 38, 12, 36, 48, 49,  3,  2,
       11,  0, 10, 13,  1, 35, 53, 33, 47, 71, 23, 73, 51, 24, 64, 50, 54,
       52,  5, 31, 28, 21, 20, 62, 72,  9, 27, 16, 25,  6, 29, 39,  8, 57,
       22, 32, 70, 30, 26, 40, 15, 59, 74, 43, 60, 58,  7, 61, 18, 19, 34,
       56, 63, 41, 55, 17, 42, 44])

In [19]:
max_accuracy_index_dcn = np.argsort(-model_stats_dcn.accuracy.values)

max_accuracy_index_dcn

array([67, 68, 69, 38, 65, 35, 66,  0, 21, 18, 37, 50, 34, 52, 46, 53, 48,
       32, 28, 17, 45, 25, 22, 51, 36, 31, 57, 19, 11, 56, 73, 44, 58, 39,
       15, 24, 71, 54,  3, 47, 40, 23, 62,  8,  6,  9, 12, 10,  1, 41,  5,
       72,  4, 49, 20, 27, 16, 13,  7, 43, 30, 29, 61, 33,  2, 60, 59, 55,
       14, 64, 26, 70, 42, 74, 63])

In [20]:
max_accuracy_index_dnn = np.argsort(-model_stats_dnn.accuracy.values)

max_accuracy_index_dnn

array([67, 69, 68, 66, 65, 39, 18, 49, 35, 27, 31, 26, 36, 32, 48, 57, 38,
       47, 45, 30, 23, 34, 40, 15, 13, 29,  8, 21, 28, 44, 37,  6, 46, 70,
       22,  0, 62, 19, 17, 56, 43,  4, 55, 11, 20, 54, 50, 41, 24, 58, 73,
       53, 16,  7,  5, 74, 25, 51,  3,  9, 52, 71, 63, 64, 61,  2, 14, 42,
       33, 59, 72, 12, 10, 60,  1])

In [21]:
max_accuracy_index_pnn = np.argsort(-model_stats_pnn.accuracy.values)

max_accuracy_index_pnn

array([66, 69, 35, 67, 65, 68, 49, 36, 48, 47, 37, 45, 70, 32, 57, 39, 38,
       26, 55, 29, 27, 14, 16, 30, 42, 34, 23, 52, 22, 51, 17, 33, 50, 24,
       46,  3, 25, 19, 28, 11, 15, 21, 64, 13, 71, 53,  4, 18, 73, 12, 59,
        9, 58, 56, 10, 31,  8, 62, 41, 54, 43,  2,  6,  7, 20, 44,  1, 40,
       61, 63, 60,  0,  5, 72, 74])

# Ensembling based on Min Loss

In [22]:
probs_df_loss = pd.read_csv('../input/lets-get-rid-of-the-patients-catboost/probs_32_0_0.csv')

In [23]:
def cal_probs_loss(model_name,model_stats_df,min_loss_idx_arr,model_iter):
    
    probs_cal_loss = np.zeros(shape=(137057,11))

    for i,idx in enumerate(min_loss_idx_arr):
    
        probs_cal_loss += pd.read_csv(get_probs_file_name(model_stats_df.iloc[idx,0],model_name)).iloc[:,1:]
    
        if i == model_iter:
        
            break
        
    probs_df_loss.iloc[:,1:] = probs_cal_loss

    #print(probs_df_loss.head())

    return probs_cal_loss
    

# Ensembling based on Max Accuracy

In [24]:
probs_df_acc = pd.read_csv('../input/lets-get-rid-of-the-patients-catboost/probs_32_0_0.csv')

In [25]:
def cal_probs_acc(model_name,model_stats_df,max_accuracy_idx_arr,model_iter):
    
    probs_cal_acc = np.zeros(shape=(137057,11))

    for i,idx in enumerate(max_accuracy_idx_arr):

        probs_cal_acc += pd.read_csv(get_probs_file_name(model_stats_df.iloc[idx,0],model_name)).iloc[:,1:]

        if i ==model_iter:

            break

    #print(probs_cal_acc.head())
    
    return probs_cal_acc
    

In [26]:
#probs_df_acc.iloc[:,1:] = cal_probs_acc('dcn',model_stats_dcn,max_accuracy_index_dcn,75)

#probs_df_acc.head()

In [27]:
#generate_submission_file(probs_df_acc)

In [28]:
#probs_acc_dcn = cal_probs_acc('dcn',model_stats_dcn,max_accuracy_index_dcn,75) 
    
#probs_acc_pnn = cal_probs_acc('pnn',model_stats_pnn,max_accuracy_index_pnn,6) 
    
#probs_acc_lgb = cal_probs_acc('lgb',model_stats_lgb,max_accuracy_index_lgb,1) 
    
#probs_df_acc.iloc[:,1:] = probs_acc_dcn + probs_acc_pnn #+probs_acc_lgb

#probs_df_acc.head()

In [29]:
#generate_submission_file(probs_df_acc)

In [30]:
# Best Public LB == 44.3508080698
probs_loss_dcn = cal_probs_loss('dcn',model_stats_dcn,min_loss_index_dcn,2) 
    
probs_loss_pnn = cal_probs_loss('pnn',model_stats_pnn,min_loss_index_pnn,2)

#probs_loss_dnn = cal_probs_loss('dnn',model_stats_dnn,min_loss_index_dnn,1) 
    
#probs_loss_cat = cal_probs_loss('catboost',model_stats_catboost,min_loss_index_cat,1) 
    
probs_df_loss.iloc[:,1:] = 1.075*probs_loss_dcn + 1.01*probs_loss_pnn #+ probs_loss_cat

probs_df_loss.head()

case_id      0-10     11-20     21-30     31-40     41-50     51-60  \
0   318439  2.699484  0.695464  1.134070  0.542088  0.528728  0.360367   
1   318440  0.000001  0.080210  0.024169  1.149419  0.056204  3.711188   
2   318441  0.675040  1.618549  2.399676  0.990677  0.353948  0.137785   
3   318442  0.078064  1.049109  4.047172  0.811801  0.183442  0.071124   
4   318443  0.000004  0.090884  0.035379  0.907488  0.040696  4.231043   

      61-70     71-80     81-90    91-100  More than 100 Days  
0  0.080884  0.091137  0.056818  0.019598            0.046362  
1  0.022070  0.946579  0.039384  0.157297            0.068480  
2  0.048818  0.021967  0.002871  0.004194            0.001474  
3  0.011184  0.002672  0.000167  0.000202            0.000062  
4  0.012550  0.799780  0.008104  0.110669            0.018404

In [31]:
generate_submission_file(probs_df_loss)

   case_id   Stay
0   318439   0-10
1   318440  51-60
2   318441  21-30
3   318442  21-30
4   318443  51-60
